[system]
description = "Simple system running only a CPU-burn component."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "burn"
img  = "no_interface.burn"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
constructor = "booter"
