[system]
description = "Test for the hello world external component"

[[components]]
name = "hw"
img  = ""
location = "github.com:gparmer/hello_world"
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"
