[system]
description = "Simplest system with crt tests."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
assurance_level = 3
baseaddr = "0x1000000"
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
assurance_level = 3
baseaddr = "0x1100000"
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
assurance_level = 3
baseaddr = "0x1200000"
constructor = "booter"

[[components]]
name = "tests"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.1"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.2"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.3"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.4"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.5"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.6"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"


[[components]]
name = "tests.7"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.8"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.9"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.10"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.11"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.12"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.13"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.14"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.15"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.16"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.17"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.18"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "tests.19"
img  = "tests.bench_lock"
implements = [{interface = "init"}]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
virt_res = [
    {vr_type = "sched", max_dynalloc = "0", instances = [
        {static_hi = {access = ["write", "read", "blocking"], name = "name_static_hi"}}, 
        {static_lo = {access = ["write", "read", "blocking"], name = "name_static_lo"}}]}
]
baseaddr = "0x1600000"
constructor = "booter"

[[virt_resources]]
server = "sched"
vr_type = "sched"
resources = [
    {instance = "static_hi", param = {core = "0", priority = "3"}},
    {instance = "static_lo", param = {core = "2", priority = "4"}}
]
