[system]
description = "Unit testing of constant value compilation"

[[components]]
name = "unit_constant_value"
img  = "tests.unit_constant_value"
constants = [{variable = "NUM_CPU", value = "4"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
baseaddr = "0x1600000"
constructor = "kernel"