[system]
description = "Simple test of blocking issue by using sod."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"},{interface = "contigmem"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.pfprr_quantum_static"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "nicmgr"
img  = "nicmgr.dummy"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}]
implements = [{interface = "nic"}]
constructor = "booter"

[[components]]
name = "netmgr"
img  = "netmgr.lwip"
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "nicmgr", interface = "nic"}]
implements = [{interface = "netmgr"}]
constructor = "booter"

[[components]]
name = "sodhc"
img  = "tests.unit_composer_lock_hi"
criticality_level = 1 
virt_res = [
    {vr_type = "net", instances = [
        {net_01 = {access = ["read","write"], name = "net_in" }}]}
]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "netmgr", interface = "netmgr"}]
constructor = "booter"

[[components]]
name = "sodlc"
img  = "tests.unit_composer_lock_lo"
criticality_level = 0 
virt_res = [
    {vr_type = "net", instances = [
        {net_01 = {access = ["read","write"], name = "net_in" }}]}
]
deps = [{srv = "sched", interface = "sched"}, {srv = "sched", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}, {srv = "capmgr", interface = "memmgr"}, {srv = "capmgr", interface = "contigmem"}, {srv = "netmgr", interface = "netmgr"}]
constructor = "booter"

[[virt_resources]]
vr_type = "net"
server = "netmgr"
resources = [
    {instance = "net_01", param = {}}
]